/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucion12;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmdcalcular = new javax.swing.JButton();
        cmdborrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnumpeliculas = new javax.swing.JTextField();
        txtnumdias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ALQUILER DE PELICULAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        cmdcalcular.setText("CALCULAR");
        cmdcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        cmdborrar.setText("BORRAR");
        cmdborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdborrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel2.setText("Numero de peliculas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 84, 130, 20));

        jLabel3.setText("Numero de dias");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 20));

        txtnumpeliculas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumpeliculasKeyTyped(evt);
            }
        });
        getContentPane().add(txtnumpeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 40, -1));

        txtnumdias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumdiasKeyTyped(evt);
            }
        });
        getContentPane().add(txtnumdias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 40, -1));

        jLabel4.setText("Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 30, 20));

        txttotal.setEditable(false);
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcalcularActionPerformed
       double nump,numd,total;
       String res;
       
       if(txtnumpeliculas.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite numero de Peliculas","Error", JOptionPane.ERROR_MESSAGE);
         txtnumpeliculas.requestFocusInWindow();
     }else if(txtnumdias.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite numero de Dias","Error", JOptionPane.ERROR_MESSAGE);
         txtnumdias.requestFocusInWindow();
     }else{
       
       nump=Double.parseDouble(txtnumpeliculas.getText());
       numd=Double.parseDouble(txtnumdias.getText());
       
       total=(nump-1)*(numd*1500);
       
       
       res=String.valueOf(total);
       txttotal.setText(res);
     }
    }//GEN-LAST:event_cmdcalcularActionPerformed

    private void cmdborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdborrarActionPerformed
      txtnumpeliculas.setText("");
      txtnumdias.setText("");
      txttotal.setText("");
      
      
      txtnumpeliculas.requestFocusInWindow();
    }//GEN-LAST:event_cmdborrarActionPerformed

    private void txtnumpeliculasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumpeliculasKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          }          
    }//GEN-LAST:event_txtnumpeliculasKeyTyped

    private void txtnumdiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumdiasKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          }  
    }//GEN-LAST:event_txtnumdiasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdborrar;
    private javax.swing.JButton cmdcalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtnumdias;
    private javax.swing.JTextField txtnumpeliculas;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
